#!/usr/bin/env bash
set -x
set -e
curl \
    -vv \
    -XPOST \
    -H'content-type: application/json' \
    -d '{"title":"1hello<script>xss</script>","latitude":55.752'$(shuf -i 100-999 -n 1)',"longitude":37.6143'$(shuf -i 100-999 -n 1)'}' \
    http://127.0.0.1:3000/api/v1/geo
